### ISSUE TITLE
Kafka 0.11 support

### ISSUE THREAD

**Issue by Poogles** [weftio/gregor#16]
https://archive.apache.org/dist/kafka/0.11.0.0/RELEASE_NOTES.html

0.11 brokers will support 0.10 clients, at the expense of memory when converting the wire protocol on the fly.  I'm guessing a simple bump of the deps should resolve this?

**Comment by ccann** [comment]
Released 0.6.0. Just bumped the dep and ran tests. Didn't notice any issues but please report any bugs you find :-) 

**This project has moved to** https://www.github.com/ccann/gregor

**Comment by Poogles** [comment]
Cheers.
