### ISSUE TITLE
Closing producers with a timeout

### ISSUE THREAD

**Issue by tolitius** [weftio/gregor#8]
First off, great library! I have a very similar code structure for kafka `0.8` that I use for a couple of projects: one file, concise, minimal dependencies, etc. Thought of rewriting it to `0.9` and pushing to github, but after looking at `gregor`'s code, I don't think I need to.

Starting from 0.9 `KafkaProducer`s (via `Producer` interface) have [another close method](https://kafka.apache.org/090/javadoc/org/apache/kafka/clients/producer/KafkaProducer.html#close(long,%20java.util.concurrent.TimeUnit)) that takes a timeout:

> If the producer is unable to complete all requests before the timeout expires, this method will fail any unsent and unacknowledged records immediately

While I can still use Java API to close producers with the `(.close producer 30 TimeUnit/SECONDS)`, it would be nice to have a consistent way to do it with `gregor`.

At first I wanted to submit a pull request, but then I saw that you use a `close` method to wrap `java.io.Closeable` which does work _for both_ producers and consumers.

Just want to see what you think about including `(close-producer [^Producer producer ^Long timeout] ...)` or another name / form, or maybe not including this at all.

**Comment by ccann** [comment]
Thanks, and thank you for mount!

I'd like to include it. The downside of one concise namespace in this case is that we can't define `close` separately for both consumers and producers without changing the name of the function and diverging a bit from the Kafka spec, as you note.

I guess one approach could be to use arity dispatch:

```clojure
(defn close
  ([^java.io.Closeable closable]
   (.close closable))
  ([^Producer p ^Long timeout]
   (assert (instance? Producer p) "Only KafkaProducer supports timeout")
   (.close p timeout TimeUnit/SECONDS)))
```

Which seems kind of odd, but maybe it's the way to go. I'm not opposed to `close-producer` and `close-consumer` either, i'd just prefer one function. Thoughts?

**Comment by tolitius** [comment]
what about a Closeable protocol instead of `close` function? i.e. this is rather a quick REPL session:

```clojure
(import '[org.apache.kafka.clients.producer KafkaProducer]
        '[org.apache.kafka.clients.consumer KafkaConsumer]
        '[java.util.concurrent TimeUnit])

(defprotocol Closeable 
  (close [this] [this timeout]))

(extend-protocol Closeable
  KafkaProducer
    (close ([p] (.close p))
           ([p timeout] (.close p timeout TimeUnit/SECONDS)))
  KafkaConsumer
    (close ([c] (.close c))))
```

then we can

```clojure
(close consumer)
(close producer)
(close producer 10)
```

**Comment by ccann** [comment]
Awesome, protocols seem like the way to go. PR more than welcome!
